import Head from 'next/head'
import styled from '@emotion/styled'
import { css } from '@emotion/react'

import styles from './index.module.css'

export default function Home() {
  return (
    <ContainerStyled>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={bold}>Hello World</div>
      <h2 className={styles.title}>css module 사용</h2>
    </ContainerStyled>
  )
}

const ContainerStyled = styled.div`
  background-color: red;
  padding: 10px;
`

const bold = css`
  font-weight: bold;
`
